// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmU_yLkqDzTr4dj4dcNAmbjHP_W9moVH8',
    appId: '1:807538238653:web:9177a692d2719c81d503d4',
    messagingSenderId: '807538238653',
    projectId: 'cuida-bem-5dcab',
    authDomain: 'cuida-bem-5dcab.firebaseapp.com',
    storageBucket: 'cuida-bem-5dcab.firebasestorage.app',
    measurementId: 'G-PKHZXTD49W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb1v2YRdR66_aUX0aa2alV0HppAx2VYzU',
    appId: '1:807538238653:android:c59b98972d0bb64dd503d4',
    messagingSenderId: '807538238653',
    projectId: 'cuida-bem-5dcab',
    storageBucket: 'cuida-bem-5dcab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRlmg8tjFleF2BKEe4YKYGCV1ck_oB9zA',
    appId: '1:807538238653:ios:a8d5a1bd105b4448d503d4',
    messagingSenderId: '807538238653',
    projectId: 'cuida-bem-5dcab',
    storageBucket: 'cuida-bem-5dcab.firebasestorage.app',
    iosBundleId: 'com.example.cuidaBem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRlmg8tjFleF2BKEe4YKYGCV1ck_oB9zA',
    appId: '1:807538238653:ios:a8d5a1bd105b4448d503d4',
    messagingSenderId: '807538238653',
    projectId: 'cuida-bem-5dcab',
    storageBucket: 'cuida-bem-5dcab.firebasestorage.app',
    iosBundleId: 'com.example.cuidaBem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmU_yLkqDzTr4dj4dcNAmbjHP_W9moVH8',
    appId: '1:807538238653:web:c6856fbaedc1e48bd503d4',
    messagingSenderId: '807538238653',
    projectId: 'cuida-bem-5dcab',
    authDomain: 'cuida-bem-5dcab.firebaseapp.com',
    storageBucket: 'cuida-bem-5dcab.firebasestorage.app',
    measurementId: 'G-WSN17YRBML',
  );
}
